### ISSUE TITLE
Bash [[ error

### ISSUE THREAD

**Issue by mardub1635** [mardub1635/chiasmus-detector#2]
```console
/chiasmus-detector$ sh run.sh 
run.sh: 10: [[: not found
-e ### downloading GerDraCor example text
--2022-09-28 17:54:35--  https://raw.githubusercontent.com/dracor-org/gerdracor/main/tei/schiller-wilhelm-tell.xml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 380543 (372K) [text/plain]
Saving to: ‘schiller-wilhelm-tell.xml.5’

schiller-wilhelm-te 100%[===================>] 371,62K  --.-KB/s    in 0,05s   

2022-09-28 17:54:35 (7,22 MB/s) - ‘schiller-wilhelm-tell.xml.5’ saved [380543/380543]

-e ### done downloading GerDraCor example text
-e ### download german spacy model if not present
-e ### done downloading german spacy model
-e ### running the experiment
initialize detector
Traceback (most recent call last):
  File "/home/marie/Documents/chiasmus-detector/chiasmus_example.py", line 47, in <module>
    main()
  File "/home/marie/Documents/chiasmus-detector/chiasmus_example.py", line 9, in main
    chidect = ChiasmusDetector(
  File "/home/marie/Documents/chiasmus-detector/chiasmus.py", line 30, in __init__
    self.fasttext_model = fasttext.load_model('./fasttext_models/wiki.de.bin')
  File "/home/marie/Documents/chiasmus-detector/chiasmus_pack/lib/python3.9/site-packages/fasttext/FastText.py", line 441, in load_model
    return _FastText(model_path=path)
  File "/home/marie/Documents/chiasmus-detector/chiasmus_pack/lib/python3.9/site-packages/fasttext/FastText.py", line 98, in __init__
    self.f.loadModel(model_path)
ValueError: ./fasttext_models/wiki.de.bin cannot be opened for loading!
```
probably the same problem as here:
https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found
?

**Comment by mardub1635** [comment]
The problem comes from the way bash is run:
```sh run.sh```
Should be:
```
bash run.sh
```
