### ISSUE TITLE
Can't find model error

### ISSUE THREAD

**Issue by mardub1635** [mardub1635/chiasmus-detector#3]
```bash
bash run.sh 
### downloading GerDraCor example text
--2022-10-03 19:53:07--  https://raw.githubusercontent.com/dracor-org/gerdracor/main/tei/schiller-wilhelm-tell.xml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 380543 (372K) [text/plain]
Saving to: ‘schiller-wilhelm-tell.xml.10’

schiller-wilhelm-te 100%[===================>] 371,62K  --.-KB/s    in 0,1s    

2022-10-03 19:53:07 (2,68 MB/s) - ‘schiller-wilhelm-tell.xml.10’ saved [380543/380543]

### done downloading GerDraCor example text
### download german spacy model if not present
### done downloading german spacy model
### running the experiment
initialize detector
Traceback (most recent call last):
  File "/home/marie/Documents/chiasmus-detector/chiasmus_example.py", line 47, in <module>
    main()
  File "/home/marie/Documents/chiasmus-detector/chiasmus_example.py", line 9, in main
    chidect = ChiasmusDetector(
  File "/home/marie/Documents/chiasmus-detector/chiasmus.py", line 35, in __init__
    self.spacy_model = spacy.load(spacy_model)
  File "/home/marie/Documents/chiasmus-detector/chiasmus_pack/lib/python3.9/site-packages/spacy/__init__.py", line 54, in load
    return util.load_model(
  File "/home/marie/Documents/chiasmus-detector/chiasmus_pack/lib/python3.9/site-packages/spacy/util.py", line 436, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'de_core_news_lg'. It doesn't seem to be a Python package or a valid path to a data directory.
```
What should I do?

**Comment by mardub1635** [comment]
Try this in the terminal:
```bash
python -m spacy download de_core_news_lg
```
then run 
```bash
bash run.sh
```
